services:
  # Backend API Service (Web Service)
  - type: web
    name: qahwatal-emarat-api
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://roobiinpandey_db_user:Nepal1590@qahwatalemarates.c5rwjak.mongodb.net/?retryWrites=true&w=majority&appName=QahwatAlemarates
      - key: JWT_SECRET
        value: e611b944e03f0f78306c104ac2f560f825df47b8da1754eb47ee84fcb405ceb0
      - key: JWT_EXPIRE
        value: 7d
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: $2a$12$92Rh/DRKSYjy8UblWX3up.cvN48mrCscC2cMsvt1wKEP7Vsm0lHT.
      - key: PASSWORD_MIN_LENGTH
        value: 8
      - key: PASSWORD_REQUIRE_UPPERCASE
        value: false
      - key: PASSWORD_REQUIRE_LOWERCASE
        value: true
      - key: PASSWORD_REQUIRE_NUMBERS
        value: true
      - key: PASSWORD_REQUIRE_SYMBOLS
        value: true
      - key: ALLOWED_ORIGINS
        value: https://qahwatal-emarat.onrender.com,https://qahwatal-emarat-frontend.onrender.com,https://qahwatal-emarat-api.onrender.com,https://*.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: FORCE_HTTPS
        value: true

  # Frontend Static Site (RECOMMENDED for React apps - cheaper and faster)
  - type: static
    name: qahwatal-emarat-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: build
    envVars:
      - key: REACT_APP_API_BASE
        value: https://qahwatal-emarat-api.onrender.com/api
