services:services:services:services:

  # Backend API Service (Web Service)

  - type: web  # Backend API Service

    name: qahwatal-emarat-api

    runtime: node  - type: web  # Backend API Service  # Backend API Service

    rootDir: server

    buildCommand: npm install    name: qahwatal-emarat-api

    startCommand: npm start

    envVars:    runtime: node  - type: web  - type: web

      - key: NODE_ENV

        value: production    rootDir: server

      - key: MONGODB_URI

        value: mongodb+srv://roobiinpandey_db_user:Nepal1590@qahwatalemarates.c5rwjak.mongodb.net/?retryWrites=true&w=majority&appName=QahwatAlemarates    buildCommand: npm install    name: qahwatal-emarat-api    name: qahwatal-emarat-api

      - key: JWT_SECRET

        value: e611b944e03f0f78306c104ac2f560f825df47b8da1754eb47ee84fcb405ceb0    startCommand: npm start

      - key: JWT_EXPIRE

        value: 7d    envVars:    runtime: node    runtime: node

      - key: ADMIN_USERNAME

        value: admin      - key: NODE_ENV

      - key: ADMIN_PASSWORD

        value: $2a$12$92Rh/DRKSYjy8UblWX3up.cvN48mrCscC2cMsvt1wKEP7Vsm0lHT.        value: production    rootDir: server    rootDir: server

      - key: PASSWORD_MIN_LENGTH

        value: 8      - key: MONGODB_URI

      - key: PASSWORD_REQUIRE_UPPERCASE

        value: false        value: mongodb+srv://roobiinpandey_db_user:Nepal1590@qahwatalemarates.c5rwjak.mongodb.net/?retryWrites=true&w=majority&appName=QahwatAlemarates    buildCommand: npm install    buildCommand: npm install

      - key: PASSWORD_REQUIRE_LOWERCASE

        value: true      - key: JWT_SECRET

      - key: PASSWORD_REQUIRE_NUMBERS

        value: true        value: e611b944e03f0f78306c104ac2f560f825df47b8da1754eb47ee84fcb405ceb0    startCommand: npm start    startCommand: npm start

      - key: PASSWORD_REQUIRE_SYMBOLS

        value: true      - key: JWT_EXPIRE

      - key: ALLOWED_ORIGINS

        value: https://qahwatal-emarat.onrender.com,https://qahwatal-emarat-api.onrender.com        value: 7d    envVars:    envVars:

      - key: RATE_LIMIT_WINDOW_MS

        value: 900000      - key: ADMIN_USERNAME

      - key: RATE_LIMIT_MAX_REQUESTS

        value: 100        value: admin      - key: NODE_ENV      - key: NODE_ENV

      - key: FORCE_HTTPS

        value: true      - key: ADMIN_PASSWORD



  # Frontend Static Site (RECOMMENDED for React apps - cheaper and faster)        value: $2a$12$92Rh/DRKSYjy8UblWX3up.cvN48mrCscC2cMsvt1wKEP7Vsm0lHT.        value: production        value: production

  - type: static

    name: qahwatal-emarat-frontend      - key: PASSWORD_MIN_LENGTH

    rootDir: frontend

    buildCommand: npm install && npm run build        value: 8      - key: MONGODB_URI      - key: MONGODB_URI

    publishDir: build

    envVars:      - key: PASSWORD_REQUIRE_UPPERCASE

      - key: REACT_APP_API_BASE

        value: https://qahwatal-emarat-api.onrender.com/api</content>        value: false        value: mongodb+srv://roobiinpandey_db_user:Nepal1590@qahwatalemarates.c5rwjak.mongodb.net/?retryWrites=true&w=majority&appName=QahwatAlemarates        sync: false # ⚠️  CRITICAL: Set this in Render dashboard with your secure MongoDB URI

<parameter name="filePath">/Volumes/PERSONAL/Qahwatal Emarat/render.yaml
      - key: PASSWORD_REQUIRE_LOWERCASE

        value: true      - key: JWT_SECRET      - key: JWT_SECRET

      - key: PASSWORD_REQUIRE_NUMBERS

        value: true        value: generate_secure_jwt_secret_here_minimum_32_characters_long        sync: false # ⚠️  CRITICAL: Generate a secure random secret (min 32 chars)

      - key: PASSWORD_REQUIRE_SYMBOLS

        value: true      - key: JWT_EXPIRE      - key: JWT_EXPIRE

      - key: ALLOWED_ORIGINS

        value: https://qahwatal-emarat.onrender.com,https://qahwatal-emarat-api.onrender.com        value: 7d        value: 7d

      - key: RATE_LIMIT_WINDOW_MS

        value: 900000      - key: ADMIN_USERNAME      - key: ADMIN_USERNAME

      - key: RATE_LIMIT_MAX_REQUESTS

        value: 100        value: admin        value: admin

      - key: FORCE_HTTPS

        value: true      - key: ADMIN_PASSWORD      - key: ADMIN_PASSWORD



  # Frontend Static Site (RECOMMENDED for React apps - cheaper and faster)        value: generate_hashed_admin_password_here        sync: false # ⚠️  CRITICAL: Set hashed password in Render dashboard

  - type: static

    name: qahwatal-emarat-frontend      - key: PASSWORD_MIN_LENGTH      - key: PASSWORD_MIN_LENGTH

    rootDir: frontend

    buildCommand: npm install && npm run build        value: 8        value: 8

    publishDir: build

    envVars:      - key: PASSWORD_REQUIRE_UPPERCASE      - key: PASSWORD_REQUIRE_UPPERCASE

      - key: REACT_APP_API_BASE

        value: https://qahwatal-emarat-api.onrender.com/api</content>        value: false        value: false

<parameter name="filePath">/Volumes/PERSONAL/Qahwatal Emarat/render.yaml
      - key: PASSWORD_REQUIRE_LOWERCASE      - key: PASSWORD_REQUIRE_LOWERCASE

        value: true        value: true

      - key: PASSWORD_REQUIRE_NUMBERS      - key: PASSWORD_REQUIRE_NUMBERS

        value: true        value: true

      - key: PASSWORD_REQUIRE_SYMBOLS      - key: PASSWORD_REQUIRE_SYMBOLS

        value: true        value: true

      - key: ALLOWED_ORIGINS      - key: ALLOWED_ORIGINS

        value: https://qahwatal-emarat.onrender.com,https://qahwatal-emarat-api.onrender.com        value: https://qahwat-al-emarat.onrender.com,https://qahwatal-emarat-api.onrender.com

      - key: RATE_LIMIT_WINDOW_MS      - key: RATE_LIMIT_WINDOW_MS

        value: 900000        value: 900000

      - key: RATE_LIMIT_MAX_REQUESTS      - key: RATE_LIMIT_MAX_REQUESTS

        value: 100        value: 100

      - key: FORCE_HTTPS      - key: FORCE_HTTPS

        value: true        value: true



  # Frontend Static Site (RECOMMENDED for React apps - cheaper and faster)services:

  - type: static  # Backend API Service

    name: qahwatal-emarat-frontend  - type: web

    rootDir: frontend    name: qahwatal-emarat-api

    buildCommand: npm install && npm run build    runtime: node

    publishDir: build    rootDir: server

    envVars:    buildCommand: npm install

      - key: REACT_APP_API_BASE    startCommand: npm start

        value: https://qahwatal-emarat-api.onrender.com/api</content>    envVars:

<parameter name="filePath">/Volumes/PERSONAL/Qahwatal Emarat/render.yaml      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # ⚠️  CRITICAL: Set this in Render dashboard with your secure MongoDB URI
      - key: JWT_SECRET
        sync: false # ⚠️  CRITICAL: Generate a secure random secret (min 32 chars)
      - key: JWT_EXPIRE
        value: 7d
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false # ⚠️  CRITICAL: Set hashed password in Render dashboard
      - key: PASSWORD_MIN_LENGTH
        value: 8
      - key: PASSWORD_REQUIRE_UPPERCASE
        value: false
      - key: PASSWORD_REQUIRE_LOWERCASE
        value: true
      - key: PASSWORD_REQUIRE_NUMBERS
        value: true
      - key: PASSWORD_REQUIRE_SYMBOLS
        value: true
      - key: ALLOWED_ORIGINS
        value: https://qahwatal-emarat.onrender.com,https://qahwatal-emarat-api.onrender.com
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: FORCE_HTTPS
        value: true

  # Frontend Static Site (RECOMMENDED for React apps - cheaper and faster)
  - type: static
    name: qahwatal-emarat-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: build
    envVars:
      - key: REACT_APP_API_BASE
        value: https://qahwatal-emarat-api.onrender.com/api

# Alternative: Web Service approach (more expensive, keeps Node.js runtime)
# - type: web
#   name: qahwatal-emarat-frontend
#   runtime: node
#   rootDir: frontend
#   buildCommand: npm install && npm run build
#   startCommand: npx serve -s build -l 3000
#   envVars:
#     - key: REACT_APP_API_BASE
#       value: https://qahwatal-emarat-api.onrender.com/api

# Alternative: Use Static Site for Frontend (Recommended for React apps)
# - type: static
#   name: qahwatal-emarat-frontend
#   rootDir: frontend
#   buildCommand: npm install && npm run build
#   publishDir: build
#   envVars:
#     - key: REACT_APP_API_BASE
#       value: https://qahwatal-emarat-api.onrender.com/api

# Database (MongoDB Atlas recommended for production)
# Note: Render provides MongoDB hosting, but MongoDB Atlas is recommended for better control
# databases:
#   - name: qahwatal-emarat-db
#     databaseName: qahwatalemarat
#     user: qahwatalemarat
